name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"  # Trigger for any branch
  pull_request:
    branches:
      - "*"  # Trigger for any pull request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run linting
        run: flake8 .

  test-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest test_main.py

  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest test_app.py

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Reading the version
        run: |
          version=$(cat versions.txt)
          new_version=$(echo $version | awk -F. '{print $1 "." $2 "." $3+1}')
          echo $new_version > version.txt
      - name: Build Docker image
        run: docker build -t mlops_deploy .
      - name: Push Docker image
        run: |
          echo "dckr_pat_tPirHLhinnT2CCWaooETwOzoCmo" | docker login -u pranavreddy08 --password-stdin
          docker tag mlops_deploy pranavreddy08/mlops_deploy:$new_version
          docker push pranavreddy08/mlops_deploy:$new_version

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: |
          ssh-keyscan -H 127.0.0.1 >> ~/.ssh/known_hosts          
          ssh root@127.0.0.1 'docker pull pranavreddy08/mlops_deploy:$new_version && docker run -d -p 8080:8080 pranavreddy08/mlops_deploy:$new_version'