name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"  # Trigger for any branch
  pull_request:
    branches:
      - "*"  # Trigger for any pull request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run linting
        run: flake8 .

  test-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest test_main.py

  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest test_app.py

  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t mlops_deploy .
      - name: Push Docker image
        run: |
          echo "cat /home/runner/.docker/config.json"
          echo "dckr_pat_tPirHLhinnT2CCWaooETwOzoCmo" | docker login -u pranavreddy08 --password-stdin
          docker tag mlops_deploy pranavreddy08/mlops_deploy:v1.0.1
          docker push pranavreddy08/mlops_deploy:v1.0.1

#  deploy:
#    needs: docker
#    runs-on: ubuntu-latest
#    steps:
#      - name: Add SSH key to known hosts
#        run: |
#          mkdir -p ~/.ssh
#          ssh-keyscan -H 127.0.0.1 >> ~/.ssh/known_hosts
#
#      - name: Deploy to Production
#        run: |
#          ssh root@127.0.0.1 'docker pull pranavreddy08/mlops_deploy:v1.0.1 && docker run -d -p 8080:8080 pranavreddy08/mlops_deploy:v1.0.1'